#############################
#     SERVICE YML          #
############################
apiVersion: v1
kind: Service
metadata:
  name: appointment-management-service
spec:
  selector:
    app: appointment-management-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
#############################
#     DEPLOYMENT YML       #
############################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-management-service
  labels:
    app: appointment-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-management-service
  template:
    metadata:
      labels:
        app: appointment-management-service
    spec:
      containers:
        - name: appointment-management-service
          image: gcr.io/phrasal-petal-444312-m0/appointment-management-service:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/appointment-management-service/actuator/health
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/appointment-management-service/actuator/health
            initialDelaySeconds: 40
            periodSeconds: 10


